export const LOGIN_ATEMPT = 'LOGIN_ATEMPT';
export const LOGIN_DONE = 'LOGIN_DONE';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION';
export const GET_PICK_UP_POSITION = 'GET_PICK_UP_POSITION';
export const GET_DROP_OFF_POSITION = 'GET_DROP_OFF_POSITION';
export const GET_PREDICTED_POSITIONS = 'GET_PREDICTED_POSITIONS';

